Repository WildCodeSchool/orleans-0919-php-ambassadeurs-de-createurs, pull requests merged in 2020-01, with the labels that each got.

#206 S03 us15
  assets/js/app.js
  assets/js/map.js
  assets/scss/home.scss
  composer.json
  composer.lock
  config/services.yaml
  package.json
  src/Controller/HomeController.php
  src/Entity/Category.php
  src/Entity/User.php
  src/Service/CoordinateService.php
  symfony.lock
  templates/home/index.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#209 S03 us49 Stylisation bouton Delete
  templates/event/_delete_form.html.twig
Labels: reviewed

#208 S02 us48 Event Fixture et affichage profil utilisateur
  assets/scss/_mixin.scss
  assets/scss/_profil_user.css
  assets/scss/_profil_user.scss
  assets/scss/_vars.scss
  assets/scss/app.scss
  src/Controller/UserController.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/UserFixtures.php
  templates/user/show.html.twig
Labels: reviewed

#207 S03_US15 fix rolesLMCO and fixtures for cities
  src/Controller/HomeController.php
  src/DataFixtures/UserFixtures.php
  templates/home/index.html.twig
Labels: reviewed

#213 dev -> master
  assets/js/app.js
  assets/js/map.js
  assets/scss/_mixin.scss
  assets/scss/_profil_user.css
  assets/scss/_profil_user.scss
  assets/scss/_search.scss
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/home.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  config/services.yaml
  package.json
  src/Controller/HomeController.php
  src/Controller/UserController.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Category.php
  src/Entity/User.php
  src/Form/SearchType.php
  src/Form/UserType.php
  src/Repository/UserRepository.php
  src/Service/CoordinateService.php
  symfony.lock
  templates/base.html.twig
  templates/event/_delete_form.html.twig
  templates/home/index.html.twig
  templates/search/_filter.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#214 S03 us18
  config/packages/security.yaml
  src/Controller/SearchController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  templates/include/_navbar.html.twig
  templates/security/login.html.twig
Labels: reviewed

#217 S03 us15 fix findByRole
  src/Controller/HomeController.php
  src/Entity/User.php
  src/Service/CoordinateService.php
  templates/home/index.html.twig
Labels: reviewed

#234 S03 us18 routes
  config/packages/security.yaml
  src/Controller/AdminBlogController.php
  src/Controller/AdminCategoryController.php
  src/Controller/AdminUserController.php
  src/Controller/BlogController.php
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  templates/blog/_delete_form.html.twig
  templates/blog/admin_blog_index.html.twig
  templates/blog/edit.html.twig
  templates/blog/index.html.twig
  templates/blog/show.html.twig
  templates/category/_delete_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/category/show.html.twig
  templates/include/_navbar_admin.html.twig
  templates/user/_delete_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
Labels: reviewed

#211 S03 us38 CRUD BRAND + fixture + stylisation edit
  assets/scss/_profil_user.scss
  src/Controller/BrandController.php
  src/DataFixtures/BrandFixtures.php
  src/Entity/Brand.php
  src/Entity/User.php
  src/Form/BrandType.php
  src/Repository/BrandRepository.php
  templates/base.html.twig
  templates/brand/_delete_form.html.twig
  templates/brand/_form.html.twig
  templates/brand/edit.html.twig
  templates/brand/index.html.twig
  templates/brand/new.html.twig
  templates/brand/show.html.twig
Labels: reviewed

#235 add a profil with form edit
  src/Controller/SecurityController.php
  src/Form/ProfilType.php
  templates/include/_navbar.html.twig
  templates/security/profile.html.twig
Labels: reviewed

#237 S04_US58_fix fix font size button
  assets/scss/home.scss
Labels: reviewed

#238 S04_US42 mailto in footer
  templates/include/_footer.html.twig
Labels: reviewed

#239 Fix event
  assets/scss/_profil_user.scss
  src/Entity/User.php
  templates/user/show.html.twig
Labels: reviewed

#236 S04_fix fix card search page
  src/Entity/User.php
  templates/search/index.html.twig
Labels: reviewed

#241 S04 us 44 fix links on cards
  templates/home/index.html.twig
  templates/search/index.html.twig
Labels: reviewed

#215 S03 us37 stylisation Brand creation
  src/Controller/BrandController.php
  src/DataFixtures/BrandFixtures.php
  templates/brand/edit.html.twig
  templates/brand/index.html.twig
  templates/brand/new.html.twig
  templates/brand/show.html.twig
Labels: reviewed

#242 S03 us18 inscription
  src/Controller/AdminUserController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/ProfilType.php
  src/Form/UserInscriptionType.php
  templates/home/index.html.twig
  templates/include/_navbar.html.twig
  templates/search/index.html.twig
Labels: reviewed

#244 S04 us23 style page créateur
  src/DataFixtures/BrandFixtures.php
  src/Entity/Brand.php
  templates/brand/show.html.twig
Labels: reviewed

#240 S04 us35.4
  assets/scss/_search.scss
  src/Controller/SearchController.php
  src/DataFixtures/UserFixtures.php
  src/Repository/UserRepository.php
  templates/home/index.html.twig
  templates/search/_filter.html.twig
  templates/search/index.html.twig
Labels: reviewed

#216 S03 us14 event map
  assets/js/app.js
  assets/js/map.js
  assets/scss/_vars.scss
  assets/scss/home.scss
  composer.lock
  phpmd.xml
  src/Controller/AdminUserController.php
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/DataFixtures/BrandFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Event.php
  src/Entity/User.php
  src/Service/CoordinateService.php
  templates/home/index.html.twig
Labels: reviewed

#243 fix change évènement by prochaine vente and links decoration
  assets/scss/app.scss
  templates/home/index.html.twig
  templates/search/index.html.twig
  templates/user/show.html.twig
Labels: reviewed

#245 S04 us48 add brand in event entity
  src/DataFixtures/BrandFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Brand.php
  src/Entity/Event.php
  templates/user/show.html.twig
Labels: reviewed

#248 fix des btn admin fontawesome
  templates/blog/admin_blog_index.html.twig
  templates/category/index.html.twig
  templates/user/index.html.twig
Labels: reviewed

#249 Fix cards search
  assets/scss/_search.scss
  assets/scss/blog.scss
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/search/index.html.twig
Labels: reviewed

#251 Fix typo general
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/blog.scss
  assets/scss/home.scss
  assets/scss/style_navbar.scss
  templates/blog/index.html.twig
Labels: reviewed

#252 intitulés navbar admin
  templates/include/_navbar_admin.html.twig
Labels: reviewed

#250 S04 us09 blog categories
  assets/scss/blog.scss
  src/DataFixtures/ArticleTagFixtures.php
  src/DataFixtures/BlogFixtures.php
  src/Entity/ArticleTag.php
  src/Entity/Blog.php
  src/Repository/ArticleTagRepository.php
  templates/blog/index.html.twig
Labels: reviewed

#254 fix fixtures user
  src/DataFixtures/UserFixtures.php
Labels: reviewed

#255 fix sur footer
  templates/include/_footer.html.twig
Labels: reviewed

#247 Fix message flash
  src/Controller/AdminBlogController.php
  src/Controller/AdminCategoryController.php
  src/Controller/AdminUserController.php
  src/Controller/BrandController.php
  src/Controller/EventController.php
Labels: reviewed

#256 S04_US09 add use assert
  src/Entity/ArticleTag.php
Labels: reviewed

#246 S03 us27 add ambassador on favorite
  assets/js/app.js
  assets/js/favorite.js
  assets/scss/_search.scss
  assets/scss/style_navbar_admin.scss
  composer.lock
  config/packages/security.yaml
  package.json
  phpmd.xml
  src/Controller/HomeController.php
  src/Controller/SearchController.php
  src/Entity/Favorite.php
  src/Entity/User.php
  src/Repository/FavoriteRepository.php
  templates/search/index.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#257 S04_fix change name argument in Brand
  src/Controller/HomeController.php
  src/Entity/Brand.php
  src/Entity/Event.php
Labels: reviewed

#253 Fix create brand and event
  src/Controller/EventController.php
  src/Form/EventType.php
  templates/brand/show.html.twig
  templates/event/_form.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/event/new.html.twig
  templates/event/show.html.twig
  templates/include/_navbar_admin.html.twig
  templates/user/show.html.twig
Labels: reviewed

#261 S04 us12
  assets/scss/_search.scss
  assets/scss/blog.scss
  src/Controller/BlogController.php
  src/Repository/BlogRepository.php
  templates/blog/index.html.twig
Labels: reviewed

#262 files about remove on favorite done
  src/Controller/SearchController.php
Labels: reviewed

#264 S03 us14 fix add creator to popup
  assets/js/map.js
  assets/scss/home.scss
Labels: reviewed

#275 S04 us04 fix blog admin add tag field
  src/Form/BlogType.php
  templates/blog/_form.html.twig
  templates/blog/admin_blog_index.html.twig
Labels: reviewed

#277 S04 fix select order
  src/Form/ProfilType.php
  src/Form/SearchType.php
Labels: reviewed

#265 S04 us60 tag index
  src/Controller/AdminArticleTagController.php
  src/Form/ArticleTagType.php
  templates/article_tag/_delete_form.html.twig
  templates/article_tag/_form.html.twig
  templates/article_tag/edit.html.twig
  templates/article_tag/index.html.twig
  templates/article_tag/new.html.twig
  templates/article_tag/show.html.twig
  templates/include/_navbar_admin.html.twig
Labels: reviewed

#278 favorite add on user_profile
  templates/search/index.html.twig
  templates/user/show.html.twig
Labels: reviewed

#276 S04 us09
  src/Controller/AdminBlogController.php
  src/Controller/BlogController.php
  templates/blog/admin_blog_show.html.twig
  templates/blog/index.html.twig
  templates/blog/show.html.twig
Labels: reviewed

#279 S04 us59 new articleTag
  src/Controller/AdminArticleTagController.php
  templates/article_tag/_form.html.twig
  templates/article_tag/new.html.twig
Labels: reviewed

#281 S04 us61 edit articleTag
  src/Controller/AdminArticleTagController.php
  templates/article_tag/edit.html.twig
Labels: reviewed

#282 S04 us62 delete articleTAg
  src/Controller/AdminArticleTagController.php
  templates/article_tag/_delete_form.html.twig
Labels: reviewed

#284 S04 optimisation request
  src/DataFixtures/BrandFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Repository/UserRepository.php
Labels: reviewed

#286 favorite on homepage realised
  assets/scss/home.scss
  templates/home/index.html.twig
Labels: reviewed

#285 Fix home btn recherche
  assets/scss/home.scss
  templates/home/index.html.twig
Labels: reviewed

#288 variable blog modifiée
  templates/blog/index.html.twig
Labels: priorité1, reviewed

#289 S04_fix admin link in navbar
  templates/include/_navbar.html.twig
Labels: reviewed

#290 fix style login
  assets/scss/_form.scss
  templates/security/login.html.twig
Labels: reviewed

#287 S03 us18 reset password with mailer
  .env
  composer.json
  composer.lock
  config/services.yaml
  phpmd.xml
  src/Controller/HomeController.php
  src/Controller/ResettingController.php
  src/Controller/SecurityController.php
  src/Entity/Brand.php
  src/Entity/User.php
  src/Form/ResettingType.php
  src/Service/CoordinateService.php
  symfony.lock
  templates/resetting/index.html.twig
  templates/resetting/mail.html.twig
  templates/resetting/request.html.twig
  templates/security/login.html.twig
Labels: reviewed

#292 S04 us60 fix add tag to show
  templates/blog/admin_blog_show.html.twig
Labels: reviewed

#293 article à la une sur page 1
  templates/blog/index.html.twig
Labels: reviewed

#298 Dev to THE MASTER
  .env
  composer.json
  composer.lock
  config/services.yaml
  phpmd.xml
  src/Controller/HomeController.php
  src/Controller/ResettingController.php
  src/Controller/SecurityController.php
  src/Entity/Brand.php
  src/Entity/User.php
  src/Form/ResettingType.php
  src/Service/CoordinateService.php
  symfony.lock
  templates/blog/admin_blog_show.html.twig
  templates/blog/index.html.twig
  templates/resetting/index.html.twig
  templates/resetting/mail.html.twig
  templates/resetting/request.html.twig
  templates/security/login.html.twig
Labels: priorité1, reviewed

#294 fix liens profils sur card
  templates/home/index.html.twig
  templates/search/index.html.twig
Labels: reviewed

#296 S04 profil
  src/Controller/SecurityController.php
  templates/search/index.html.twig
  templates/security/editProfile.html.twig
  templates/security/profile.html.twig
  templates/user/show.html.twig
Labels: priorité1, reviewed

#300 S04 fix height home image
  assets/scss/home.scss
Labels: reviewed

#301 S04 fix wrong layout extended in article show
  templates/blog/show.html.twig
Labels: reviewed

#302 S04 fix font size
  assets/scss/_vars.scss
Labels: reviewed

#297 Fix fixtures img
  assets/images/placeholder_profil_grey.png
  src/DataFixtures/UserFixtures.php
  templates/search/index.html.twig
Labels: reviewed

#303 S04 us17 newsletter inscription
  .env
  assets/scss/home.scss
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/HomeController.php
  symfony.lock
  templates/home/_form_newsletter.html.twig
  templates/home/index.html.twig
Labels: reviewed

#340 S05 us66 favorite list of user
  src/Controller/FavoriteController.php
  src/Repository/FavoriteRepository.php
  templates/favorite/index.html.twig
  templates/include/_navbar.html.twig
Labels: reviewed

#343 S05 us63 unsubsribe newsletter
  src/Controller/HomeController.php
  templates/home/_form_newsletter.html.twig
  templates/home/index.html.twig
  templates/home/unsubscribe_newsletter.html.twig
Labels: reviewed

#342 S05 us08 upload img blog
  assets/scss/blog.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  src/DataFixtures/BlogFixtures.php
  src/Entity/Blog.php
  src/Form/BlogType.php
  symfony.lock
  templates/blog/_form.html.twig
  templates/blog/admin_blog_show.html.twig
  templates/blog/index.html.twig
  templates/blog/show.html.twig
Labels: reviewed

#345 fix on picture of favorite list of user
  templates/favorite/index.html.twig
  templates/include/_navbar.html.twig
  templates/security/profile.html.twig
Labels: reviewed

#344 S04 us2
  src/Controller/BrandController.php
  src/Entity/Brand.php
  src/Form/ChosenCreatorType.php
  templates/brand/index.html.twig
  templates/include/_navbar_admin.html.twig
Labels: reviewed

#350 S05 us01
  assets/scss/app.scss
  assets/scss/blog.scss
  assets/scss/subscription.scss
  src/Controller/SubscriptionController.php
  src/DataFixtures/SubscriptionFixtures.php
  src/Entity/Subscription.php
  src/Repository/SubscriptionRepository.php
  templates/include/_footer.html.twig
  templates/subscription/index.html.twig
Labels: reviewed

#351 S05 us19 profil picture upload
  assets/js/map.js
  assets/scss/_profil_user.scss
  assets/scss/blog.scss
  config/packages/vich_uploader.yaml
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Blog.php
  src/Entity/User.php
  src/Form/BlogType.php
  src/Form/ProfilType.php
  templates/favorite/index.html.twig
  templates/home/index.html.twig
  templates/search/index.html.twig
  templates/security/profile.html.twig
  templates/user/show.html.twig
Labels: reviewed

#352 fix pagination nb resultats page1 et autres pages
  src/Controller/BlogController.php
  src/Repository/BlogRepository.php
  templates/blog/index.html.twig
Labels: reviewed

#353 S05 us14 map null coordinates case
  assets/js/map.js
  src/Controller/AdminUserController.php
  src/Controller/SecurityController.php
  src/Service/CoordinateService.php
Labels: reviewed

#359 S05 us10 FAQ admin read
  src/Controller/AdminQuestionController.php
  src/DataFixtures/QuestionCategoryFixtures.php
  src/DataFixtures/QuestionFixtures.php
  src/Entity/Question.php
  src/Entity/QuestionCategory.php
  src/Form/QuestionType.php
  src/Repository/QuestionCategoryRepository.php
  src/Repository/QuestionRepository.php
  templates/include/_navbar_admin.html.twig
  templates/question/_delete_form.html.twig
  templates/question/_form.html.twig
  templates/question/admin_index.html.twig
  templates/question/admin_show.html.twig
  templates/question/edit.html.twig
  templates/question/new.html.twig
Labels: reviewed

#363 remove the link on profil user
  templates/security/profile.html.twig
Labels: reviewed

#361 add mailto
  templates/user/show.html.twig
Labels: reviewed

#366 S05 us10 new
  src/Controller/AdminQuestionController.php
  src/Form/QuestionType.php
  templates/question/_form.html.twig
  templates/question/edit.html.twig
  templates/question/new.html.twig
Labels: reviewed

#362 files about concept done
  assets/scss/app.scss
  assets/scss/concept.scss
  src/Controller/ConceptController.php
  templates/concept/concept_ambassador.html.twig
  templates/concept/concept_creator.html.twig
  templates/concept/index.html.twig
  templates/include/_footer.html.twig
Labels: reviewed

#364 template page ambassadeur
  assets/scss/_profil_user.scss
  templates/user/show.html.twig
Labels: priorité1, reviewed

#374 S05_fix_form_css
  assets/scss/_profil_user.scss
  assets/scss/blog.scss
Labels: reviewed

#349 add checkbox mentions légales
  src/Form/ProfilType.php
  src/Form/UserInscriptionType.php
  templates/user/_form.html.twig
Labels: reviewed

#367 fix admin menu done
  assets/scss/app.scss
  assets/scss/style_navbar_admin.scss
  templates/base.html.twig
  templates/include/_navbar_admin.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
Labels: reviewed

#368 S05 fix placeholder
  assets/images/blog_placeholder.png
  src/DataFixtures/BlogFixtures.php
  src/DataFixtures/UserFixtures.php
  templates/blog/index.html.twig
  templates/blog/show.html.twig
  templates/favorite/index.html.twig
  templates/home/index.html.twig
  templates/search/index.html.twig
  templates/security/profile.html.twig
  templates/user/show.html.twig
Labels: reviewed

#369 S05 us10 delete
  src/Controller/AdminQuestionController.php
  templates/question/_delete_form.html.twig
Labels: reviewed

#375 S05 us01 read - mise en place du CRUD (modification de la partie Read et séparation de l'index de la partie visiteur et de l'admin)
  src/Controller/AdminSubscriptionController.php
  src/Controller/SubscriptionController.php
  src/Form/SubscriptionType.php
  templates/include/_navbar_admin.html.twig
  templates/subscription/_delete_form.html.twig
  templates/subscription/_form.html.twig
  templates/subscription/admin_index.html.twig
  templates/subscription/edit.html.twig
  templates/subscription/index.html.twig
  templates/subscription/new.html.twig
  templates/subscription/show.html.twig
Labels: reviewed

#377 S05 fix placeholder JS popup
  assets/js/map.js
  assets/scss/home.scss
  src/DataFixtures/UserFixtures.php
Labels: reviewed

#378 S05 us10 public
  assets/scss/app.scss
  assets/scss/faq.scss
  composer.json
  composer.lock
  src/Controller/QuestionController.php
  src/DataFixtures/QuestionFixtures.php
  templates/include/_footer.html.twig
  templates/question/index.html.twig
Labels: reviewed

#381 S04 us65
  src/Controller/BrandController.php
  src/Entity/Brand.php
  src/Form/HasSubscribeType.php
  templates/brand/index.html.twig
Labels: reviewed

#382 Update des tarifs d'abonnement
  src/Controller/AdminSubscriptionController.php
  src/Form/SubscriptionType.php
  templates/subscription/_form.html.twig
  templates/subscription/admin_index.html.twig
  templates/subscription/edit.html.twig
Labels: reviewed

#383 correction icon favorite on homepage
  templates/home/index.html.twig
Labels: reviewed

#385 fix sur footer
  templates/include/_footer.html.twig
Labels: reviewed

#380 add link on label
  src/Form/ProfilType.php
  src/Form/UserInscriptionType.php
  templates/security/_formProfile.html.twig
  templates/security/editProfile.html.twig
  templates/user/_form.html.twig
Labels: question

#379 correction about concept page
  src/Controller/ConceptController.php
  templates/concept/concept_ambassador.html.twig
  templates/concept/concept_creator.html.twig
  templates/concept/index.html.twig
Labels: reviewed

#384 ajout du bouton Je m'abonne
  templates/subscription/index.html.twig
Labels: reviewed

#386 fix on admin menu
  templates/include/_navbar_admin.html.twig
Labels: reviewed

#402 Fix apache
  composer.json
  composer.lock
  public/.htaccess
  symfony.lock
Labels: priorité1, reviewed

#393 fix icones home responsive
  assets/scss/home.scss
  templates/home/index.html.twig
Labels: reviewed

#394 S05_US44_fix display most favorited ambassador
  src/Controller/HomeController.php
  src/DataFixtures/FavoriteFixtures.php
  src/Repository/UserRepository.php
Labels: reviewed

#396 modification mise en page newsletter
  assets/images/newsletter_placeholder.jpg
  assets/scss/_form.scss
  assets/scss/home.scss
  templates/home/_form_newsletter.html.twig
  templates/home/index.html.twig
  templates/include/_footer.html.twig
Labels: reviewed

#397 S05 us67 index
  assets/scss/app.scss
  assets/scss/gallery.scss
  config/packages/vich_uploader.yaml
  src/Controller/GalleryController.php
  src/Controller/HomeController.php
  src/DataFixtures/GalleryFixtures.php
  src/Entity/Brand.php
  src/Entity/Gallery.php
  src/Form/GalleryType.php
  src/Repository/GalleryRepository.php
  templates/base.html.twig
  templates/gallery/_delete_form.html.twig
  templates/gallery/_form.html.twig
  templates/gallery/index.html.twig
  templates/security/_creatorPartProfile.html.twig
Labels: reviewed

#400 remove edit user for admin
  src/Controller/AdminUserController.php
  src/Entity/Brand.php
  src/Entity/User.php
  templates/brand/_delete_form.html.twig
  templates/brand/edit.html.twig
  templates/user/_delete_form.html.twig
  templates/user/index.html.twig
Labels: reviewed

#401 S05 us67
  src/Controller/CompanyController.php
  src/Controller/ConceptController.php
  templates/company/cgu_index.html.twig
  templates/company/cgv_index.html.twig
  templates/company/concept_index.html.twig
  templates/company/confidentiality_index.html.twig
  templates/company/legal_mentions_index.html.twig
  templates/include/_footer.html.twig
Labels: reviewed

#404 S05 us67 delete
  assets/scss/gallery.scss
  src/Controller/GalleryController.php
  src/DataFixtures/GalleryFixtures.php
  templates/gallery/_delete_aria_form.html.twig
  templates/gallery/_delete_form.html.twig
  templates/gallery/index.html.twig
Labels: reviewed

#406 Fix blog updated
  src/Controller/AdminBlogController.php
  src/Form/BlogType.php
  templates/blog/show.html.twig
Labels: reviewed

#407 S05_fix_flash add close button
  templates/base.html.twig
Labels: reviewed

#409 S05 fix newsletter
  assets/scss/home.scss
  templates/home/unsubscribe_newsletter.html.twig
Labels: reviewed

#411 S05_US44_fix fix jointure
  src/Repository/UserRepository.php
Labels: reviewed

#412 S05_fix overflow on home
  assets/scss/home.scss
Labels: reviewed

#405 errors pages done
  assets/images/error403.png
  assets/images/error404.png
  assets/images/error500.png
  assets/scss/app.scss
  assets/scss/errors.scss
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/layout_errors.html.twig
Labels: reviewed

#408 S05 us45
  src/Controller/HomeController.php
  src/Repository/BrandRepository.php
  templates/home/index.html.twig
Labels: reviewed

#410 S05_fix_faq w3c
  templates/question/index.html.twig
  templates/search/index.html.twig
Labels: reviewed

#413 S05_fix font weight
  assets/scss/_vars.scss
Labels: reviewed

#414 add title on errors pages
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: reviewed

#415 S05_fix_form button style
  src/Controller/AdminArticleTagController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminSubscriptionController.php
  templates/article_tag/index.html.twig
  templates/article_tag/show.html.twig
  templates/blog/admin_blog_show.html.twig
  templates/blog/new.html.twig
  templates/brand/_delete_form.html.twig
  templates/brand/index.html.twig
  templates/category/index.html.twig
  templates/event/_delete_form.html.twig
  templates/event/index.html.twig
  templates/question/admin_show.html.twig
  templates/question/new.html.twig
  templates/subscription/_delete_form.html.twig
  templates/subscription/edit.html.twig
  templates/user/index.html.twig
Labels: reviewed

#416 S05 us64 security
  config/packages/security.yaml
  src/Controller/AdminBrandController.php
  src/Controller/BrandController.php
  src/Controller/FavoriteController.php
  src/Controller/SecurityController.php
  templates/resetting/request.html.twig
Labels: reviewed

#418 Fix login and password page
  assets/scss/app.scss
  templates/resetting/request.html.twig
  templates/security/login.html.twig
Labels: reviewed

#417 fix alert on favorite
  assets/js/favorite.js
Labels: reviewed

#419 fix on search button homepage done
  assets/scss/home.scss
  templates/home/index.html.twig
Labels: reviewed

#421 S05 fix filter on search page
  templates/search/_filter.html.twig
Labels: reviewed

#424 dev to master 17/01
  assets/js/favorite.js
  assets/scss/home.scss
  templates/home/index.html.twig
  templates/search/_filter.html.twig
Labels: reviewed

#425 S05 fix picture on homepage
  assets/scss/home.scss
  templates/home/index.html.twig
Labels: reviewed

#428 page concept
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/base.html.twig
  templates/blog/index.html.twig
  templates/company/concept_index.html.twig
Labels: reviewed

#431 modif abonnement
  templates/subscription/index.html.twig
Labels: reviewed

#429 S06 fix typo
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/style_footer.scss
  assets/scss/style_navbar.scss
  templates/base.html.twig
  templates/blog/index.html.twig
Labels: reviewed

#430 S05 us69 user manual
  templates/admin/includes/_introduction.html.twig
  templates/admin/includes/_navigation-menu.html.twig
  templates/admin/index.html.twig
Labels: reviewed

#432 btn contacter si abonné
  templates/user/show.html.twig
Labels: reviewed

#433 fix about create button on admin category
  templates/category/index.html.twig
Labels: reviewed

#434 New search card
  assets/scss/_search.scss
  assets/scss/style_navbar.scss
  src/DataFixtures/DutyFixtures.php
  src/DataFixtures/UserFixtures.php
  templates/search/_filter.html.twig
  templates/search/index.html.twig
Labels: reviewed

#436 S05 fix admin user index
  templates/user/_delete_form.html.twig
  templates/user/index.html.twig
Labels: reviewed

#437 S06 event brand admin correction
  src/Controller/AdminBrandController.php
  src/Controller/AdminUserController.php
  templates/brand/admin_delete_form.html.twig
  templates/brand/index.html.twig
  templates/event/admin_delete_form.html.twig
  templates/event/index.html.twig
Labels: reviewed

#438 S06_fix_navbarAdmin position fixed
  templates/include/_navbar_admin.html.twig
Labels: reviewed

#439 fix btn contacter ambassadeur
  templates/user/show_ambassador.html.twig
Labels: reviewed

#440 corrections on user manual
  templates/admin/includes/_introduction.html.twig
  templates/admin/includes/_navigation-menu.html.twig
Labels: reviewed

#441 fix on faq file
  templates/question/index.html.twig
Labels: reviewed

#442 S06_fix_link_card creator
  templates/home/_cardCreators.html.twig
Labels: reviewed

#446 S06 fix migrations
  src/Migrations/Version20200121083508.php
Labels: reviewed

#447 S06_fix_optimization request on home page
  src/Controller/HomeController.php
  src/Repository/BrandRepository.php
  src/Repository/UserRepository.php
Labels: reviewed

#450 S06_fix_optimization request on search page
  src/Repository/UserRepository.php
Labels: reviewed

#451 Fix steven21 01
  assets/scss/_search.scss
  assets/scss/subscription.scss
  src/Controller/GalleryController.php
  src/Form/BrandType.php
  src/Form/UserInscriptionType.php
  templates/blog/show.html.twig
  templates/search/index.html.twig
  templates/user/_form.html.twig
  templates/user/new.html.twig
  templates/user/show_ambassador.html.twig
  templates/user/show_creator.html.twig
Labels: reviewed

#452 Fix homepage2
  assets/images/Homepage_Newsletter.jpg
  assets/scss/app.scss
  assets/scss/home.scss
  templates/home/_cardAmbassadors.html.twig
  templates/home/_cardCreators.html.twig
  templates/home/_map.html.twig
  templates/home/_reasonAmbassador.html.twig
  templates/home/_reasonCreator.html.twig
  templates/home/_search.html.twig
  templates/home/index.html.twig
Labels: reviewed

#454 S06_fix_admin_faq
  templates/question/admin_index.html.twig
Labels: reviewed

#455 S06 fix profil
  assets/scss/home.scss
  templates/security/_ambassadorPartProfile.html.twig
  templates/security/_creatorPartProfile.html.twig
  templates/security/profile.html.twig
Labels: reviewed

#456 S06_fix_optimization request on search page fix duty join
  src/Repository/UserRepository.php
Labels: reviewed

#458 S06_fix_overflow
  assets/scss/_search.scss
  templates/search/_filter.html.twig
  templates/search/index.html.twig
Labels: reviewed

#460 S06_fix_img newsletter
  assets/images/Homepage_Newsletter.jpg
  assets/images/Homepage_Newsletter.webp
  templates/home/index.html.twig
Labels: reviewed

#461 harmonisation admin
  assets/scss/app.scss
  templates/admin/includes/_navigation-menu.html.twig
  templates/article_tag/index.html.twig
  templates/blog/admin_blog_index.html.twig
  templates/brand/index.html.twig
  templates/event/index.html.twig
  templates/question/admin_index.html.twig
  templates/user/index.html.twig
Labels: reviewed

#463 fix mail footer and role in search page
  templates/include/_footer.html.twig
  templates/search/index.html.twig
Labels: reviewed

#464 S06_fix_responsive_home
  assets/scss/home.scss
  templates/home/_reasonAmbassador.html.twig
  templates/home/_search.html.twig
Labels: reviewed

#465 S06_fix_responsive_ambassador
  templates/user/show_ambassador.html.twig
Labels: reviewed

#466 fixEventShow
  templates/event/show.html.twig
Labels: reviewed

#467 S06_fix change max size of profile photo
  src/Entity/User.php
Labels: reviewed

#468 S06_fix favorites in homepage
  templates/home/_cardAmbassadors.html.twig
  templates/home/_cardCreators.html.twig
Labels: priorité1, reviewed
